Fix discrepency
BowDown097/RRBot pull request #6
Opened 2022-02-04 02:27 UTC by DannyParker0001

Hi BowDown097,

Whilst using RRBot I noticed that two users, Danny Parker and Cashmere a Rolex were getting noticeably less successful gambles than other users. I believe you may have some uncommited changes that led to this.
Upon further investigation, there seemed to be no check to ensure these users have lower rates, so I added them in this PR.  

Kind regards,
Danny

2022-02-04 03:15 UTC, binex-dsk requested changes

2022-02-04 03:15 UTC, binex-dsk commented on Modules/Gambling.cs
> +        if (Context.User.Id == 212496184776851456 || Context.User.Id == 294538745296846858)
This is missing user ID `874458978577428551`. Please fix this immediately and merging will be considered.

2022-02-04 12:32 UTC, binex-dsk approved these changes

2022-02-04 13:01 UTC, Realswitzer requested changes
Create Venezuela (make it `odds *= 10000.5`)

2022-02-04 13:40 UTC, DannyParker0001 commented
> Create Venezuela (make it `odds *= 10000.5`)

Sorry this is currently held back by #7, perhaps this should be added in a new PR?

2022-02-04 13:46 UTC, Realswitzer commented
oh k, will review again

2022-02-04 13:46 UTC, Realswitzer approved these changes
ok it workie

2022-02-09 08:26 UTC, DannyParker0001 commented
@BowDown097 Can we get an ETA on the merge?

2022-02-11 02:50 UTC, binex-dsk commented
@BowDown097 This LGTM. Can we get a merge? This is needed ASAP as it fixes several long standing bugs and issues with the bot.

2022-02-16 20:21 UTC, Realswitzer approved these changes

2022-06-09 18:55 UTC, closed without merging